In [1]:
import groupy.garray as ga

In [15]:
import groupy.gconv as gc

In [20]:
import groupy.gfunc as gf

In [2]:
import numpy as np

In [21]:
import tensorflow as tf


ModuleNotFoundError: No module named 'tensorflow'

In [ ]:

from groupy.gconv.tensorflow_gconv.splitgconv2d import gconv2d, gconv2d_util

# Construct graph
x = tf.placeholder(tf.float32, [None, 9, 9, 3])

gconv_indices, gconv_shape_info, w_shape = gconv2d_util(
    h_input='Z2', h_output='D4', in_channels=3, out_channels=64, ksize=3)
w = tf.Variable(tf.truncated_normal(w_shape, stddev=1.))
y = gconv2d(input=x, filter=w, strides=[1, 1, 1, 1], padding='SAME',
            gconv_indices=gconv_indices, gconv_shape_info=gconv_shape_info)

gconv_indices, gconv_shape_info, w_shape = gconv2d_util(
    h_input='D4', h_output='D4', in_channels=64, out_channels=64, ksize=3)
w = tf.Variable(tf.truncated_normal(w_shape, stddev=1.))
y = gconv2d(input=y, filter=w, strides=[1, 1, 1, 1], padding='SAME',
            gconv_indices=gconv_indices, gconv_shape_info=gconv_shape_info)

# Compute
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
y = sess.run(y, feed_dict={x: np.random.randn(10, 9, 9, 3)})
sess.close()

print y.shape  # (10, 9, 9, 512) 

In [3]:
x = np.array([0,1], dtype=np.int16)

In [4]:
# TEST Z2 ARRAY

# check_wallpaper_group function


In [5]:
import groupy.garray.Z2_array as z2

In [6]:
a = z2.rand(
    minu=-1, maxu=2,
    minv=-1, maxv=2,
    size=(2, 2)
    )

e = z2.identity()

print(a, e, sep="\n\n")

Z2
array([[[ 0, -1],
        [ 0, -1]],

       [[ 1,  1],
        [-1, -1]]])

Z2
array([0, 0])


In [7]:
mesh = z2.meshgrid()
print(mesh)

Z2
array([[[-1, -1],
        [-1,  0],
        [-1,  1]],

       [[ 0, -1],
        [ 0,  0],
        [ 0,  1]],

       [[ 1, -1],
        [ 1,  0],
        [ 1,  1]]])


In [8]:
mesh.shape

(3, 3)